name: 03-01 - Webhook

on:
    repository_dispatch:
        types: [ejecutar_cron]

jobs:
    schedule:
        runs-on: ubuntu-24.04
        steps:
            - name: Saludar
              run: echo "Hola desde Github Actions"