name: 05 - ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Preparar entorno
        id: setup-uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
        
      - name: Instalar dependencias
        run: uv sync
      
      - name: Mostrar version Python
        run: uv run python --version
      
      - name: Mostrar carpeta actual y listar directorio
        run: pwd && ls -la

  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Preparar entorno
        uses: astral-sh/setup-uv@v7

      - name: Instalar dependencias
        run: uv sync
      
      - name: Test with Pytest
        run: uv run --frozen pytest
        env:
          PYTHONPATH: .

  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Preparar entorno
        uses: astral-sh/setup-uv@v7

      - name: Instalar dependencias
        run: uv sync

      - name: Linter with Ruff
        run: uv run ruff check .

  type_checker:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Preparar entorno
        uses: astral-sh/setup-uv@v7

      - name: Instalar dependencias
        run: uv sync
      
      - name: Type checker with Pyrefly
        run: uv run pyrefly check
